### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by RexWzh** [jiegillet/QRCode.jl#32]
Part of the plan follows the discussion here: https://discourse.julialang.org/t/ann-qrcode-jl-create-qr-code-within-julia/26923/

- [ ] #47
- [ ] #33
- [x] ~#38~
- [ ] Interact with other tools, for example, [zbar](https://github.com/ZBar/ZBar), OpenCV and etc.
- [x] ~Some structural design, for example, use `QRCode` to represent a QR code matrix, and allow operations on it like `plot` or `exportimage`.~
- [ ] Deploy this as a service using Genie.jl(as suggested in the [forem](https://forem.julialang.org/rexwzh/coder-decoder-for-qr-codes-ospp22-work-product-3gn4))
